In [48]:
# Import required libraries
import pandas as pd

# Load the dataset
ds_jobs = pd.read_csv("customer_train.csv")

# View the dataset
ds_jobs.head()

,student_id,city,city_development_index,gender,relevant_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,job_change
0,8949,city_103,0.920,Male,Has relevant experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevant experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevant experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevant experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevant experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [49]:
# Create a copy of ds_jobs for transforming
ds_jobs_transformed = ds_jobs.copy()

In [50]:
# View the dataset
ds_jobs_transformed.head()

,student_id,city,city_development_index,gender,relevant_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,job_change
0,8949,city_103,0.920,Male,Has relevant experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevant experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevant experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevant experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevant experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [51]:
# Obtain a brief summary of the ds_jobs_transformed DataFrame using the info() function
ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  job_change              19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [52]:
# Check for the unique values in the job_change column
ds_jobs_transformed["job_change"].unique()

array([1., 0.])

In [53]:
#convert "job_change" column to object data type
ds_jobs_transformed["job_change"]= ds_jobs_transformed["job_change"].astype("object")

In [54]:
ds_jobs_transformed.columns

Index(['student_id', 'city', 'city_development_index', 'gender',
       'relevant_experience', 'enrolled_university', 'education_level',
       'major_discipline', 'experience', 'company_size', 'company_type',
       'last_new_job', 'training_hours', 'job_change'],
      dtype='object')

In [55]:
""" Loop over each column and convert to boolean data type if column is of object data type and with only two unique values; else convert to int32 if column is of int64 data type;
 else if column is of float64, convert to float16, else convert to category data type if column is of object data type and the number of unique is not two. """

for col in ds_jobs_transformed.columns:
    if (ds_jobs_transformed[col].dtype == "object") and (ds_jobs_transformed[col].nunique()==2):
       ds_jobs_transformed[col]= ds_jobs_transformed[col].astype("bool")

    elif ds_jobs_transformed[col].dtype == "int64":
       ds_jobs_transformed[col]= ds_jobs_transformed[col].astype("int32")

    elif ds_jobs_transformed[col].dtype == "float64":
       ds_jobs_transformed[col]= ds_jobs_transformed[col].astype("float16")

    elif (ds_jobs_transformed[col].dtype == "object") and (ds_jobs_transformed[col].nunique()!=2):
       ds_jobs_transformed[col]= ds_jobs_transformed[col].astype("category")

In [56]:
# Check for the unique values in the enrolled_university column
ds_jobs_transformed["enrolled_university"].unique()

['no_enrollment', 'Full time course', NaN, 'Part time course']
Categories (3, object): ['Full time course', 'Part time course', 'no_enrollment']

In [57]:
ds_jobs_transformed["enrolled_university"]= ds_jobs_transformed["enrolled_university"].cat.set_categories(new_categories=['no_enrollment','Part time course','Full time course'], ordered=True)

In [58]:
# Check for the unique values in the education_level column
ds_jobs_transformed["education_level"].unique()

['Graduate', 'Masters', 'High School', NaN, 'Phd', 'Primary School']
Categories (5, object): ['Graduate', 'High School', 'Masters', 'Phd', 'Primary School']

In [59]:
ds_jobs_transformed["education_level"]= ds_jobs_transformed["education_level"].cat.set_categories(new_categories=['Primary School', 'High School','Graduate', 'Masters', 'Phd'], ordered=True)

In [60]:
ds_jobs_transformed["experience"]= ds_jobs_transformed["experience"].cat.set_categories(new_categories=["<1","1","2","3","4","5","6,""7","8","9","10","11","12","13","14","15","16","17","18","19","20", ">20"], ordered=True)

In [61]:
# Check for the unique values in the last_new_job column
ds_jobs_transformed["last_new_job"].unique()

['1', '>4', 'never', '4', '3', '2', NaN]
Categories (6, object): ['1', '2', '3', '4', '>4', 'never']

In [62]:
ds_jobs_transformed["last_new_job"]= ds_jobs_transformed["last_new_job"].cat.set_categories(new_categories=["never","1","2", "3", "4", ">4"], ordered=True)

In [63]:
# Check for the unique values in the company_size column
ds_jobs_transformed["company_size"].unique()

[NaN, '50-99', '<10', '10000+', '5000-9999', '1000-4999', '10-49', '100-499', '500-999']
Categories (8, object): ['10-49', '100-499', '1000-4999', '10000+', '50-99', '500-999', '5000-9999', '<10']

In [64]:
ds_jobs_transformed["company_size"]= ds_jobs_transformed["company_size"].cat.set_categories(new_categories=['<10','10-49', '50-99','100-499', '500-999', '1000-4999', '5000-9999','10000+'], ordered=True)

In [65]:
ds_jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  job_change              19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [66]:
ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int32
 1   city                    19158 non-null  category
 2   city_development_index  19158 non-null  float16
 3   gender                  14650 non-null  category
 4   relevant_experience     19158 non-null  bool
 5   enrolled_university     18772 non-null  category
 6   education_level         18698 non-null  category
 7   major_discipline        16345 non-null  category
 8   experience              16849 non-null  category
 9   company_size            13220 non-null  category
 10  company_type            13018 non-null  category
 11  last_new_job            18735 non-null  category
 12  training_hours          19158 non-null  int32
 13  job_change              19158 non-null  bool
dtypes: bool(2), category(9), float16(1), int32(2)
memory usage: 400.2 KB